# 使用线上 PHP 镜像作为基础基础镜像
FROM registry.verystar.net/library/php:5.4.45-fpm-v2

RUN apt-get update && apt-get install -y --no-install-recommends git ssh-client \
  && rm -r /var/lib/apt/lists/*

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /tmp
ENV COMPOSER_VERSION 1.8.0

RUN set -eux; \
  curl --silent --fail --location --retry 3 --output /usr/bin/composer --url https://getcomposer.org/download/1.8.0/composer.phar; \
  chmod +x /usr/bin/composer

CMD ["composer"]
