ARG VERSION=1.0.0.152

FROM ghcr.io/agent-infra/sandbox:${VERSION}
LABEL maintainer="www.verystar.net"
RUN /usr/local/bin/pip3 install --upgrade --no-cache-dir \
    numpy \
    pandas \
    scipy \
    matplotlib \
    seaborn \
    scikit-learn \
    statsmodels \
    polars \
    pyarrow \
    duckdb \
    openpyxl \
    xlrd \
    xlsxwriter \
    lxml \
    requests \
    httpx \
    sqlalchemy \
    pymysql \
    tqdm \
    plotly