name: Drone Server

on:
  push:
    branches:
      - main
    paths:
      # - "drone-server/**"
      - ".github/workflows/drone-server.yaml"
  workflow_dispatch:

permissions:
  packages: write

env:
  IMAGE_NAME: drone-server
  IMAGE_LATEST_TAG: 2.23.0

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - version: 2.23.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkou Harness Drone
        uses: actions/checkout@v4
        with:
          repository: harness/gitness
          ref: v${{ matrix.version }}
          path: ${{ env.IMAGE_NAME }}

      - name: Setup Go Version
        uses: actions/setup-go@v5
        with:
          go-version: "^1.21.3"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get Semver Version
        id: get-version
        run: |
          npm install -g semver
          echo "version=$(semver --coerce ${{ matrix.version }})" >> $GITHUB_OUTPUT

      - name: Semver Parse
        uses: terradatum/semver-action@main
        id: semver
        with:
          version: ${{ steps.get-version.outputs.version }}

      - name: Go Build
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
        run: |
          cd ${{ env.IMAGE_NAME }}
          mkdir -p release/linux/amd64
          go version
          go env
          go build -ldflags '-s' -tags "nolimit" -o release/linux/amd64/drone-server ./cmd/drone-server/

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
            verystar/${{ env.IMAGE_NAME }}
            registry.verystar.net/library/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.version }}
            type=raw,value=${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
            type=raw,value=${{ steps.semver.outputs.major }}
            type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ACR Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.verystar.net
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "${{ env.IMAGE_NAME }}/"
          push: true
          file: ${{ env.IMAGE_NAME }}/docker/Dockerfile.server.linux.amd64
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
