name: Kaniko

on:
  push:
    branches:
      - main
    paths:
      - "kaniko-executor/**"
      - ".github/workflows/kaniko-executor.yaml"
  workflow_dispatch:

permissions:
  packages: write

env:
  IMAGE_NAME: kaniko-executor
  IMAGE_LATEST_TAG: 1.10.0

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image:
          - executor
          - executor-debug
          - executor-slim

        include:
          - image: executor
            version: 1.10.0
            tag: 1.10.0
          - image: executor-debug
            version: 1.10.0
            tag: 1.10.0-debug
          - image: executor-slim
            version: 1.10.0
            tag: 1.10.0-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node Version
        uses: actions/setup-node@v6
        with:
          node-version: 18.x

      - name: Get Semver Version
        id: get-version
        run: |
          npm install -g semver
          echo "version=$(semver ${{ matrix.version }})" >> $GITHUB_OUTPUT

      - name: Semver Parse
        uses: terradatum/semver-action@main
        id: semver
        with:
          version: ${{ steps.get-version.outputs.version }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
            verystar/${{ env.IMAGE_NAME }}
            registry.verystar.net/library/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.tag }}
            type=raw,value=${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }},enable=${{ matrix.version == matrix.tag }}
            type=raw,value=${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}-debug,enable=${{ endsWith(matrix.tag, '-debug') }}
            type=raw,value=${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}-slim,enable=${{ endsWith(matrix.tag, '-slim') }}
            type=raw,value=${{ steps.semver.outputs.major }},enable=${{ matrix.version == matrix.tag }}
            type=raw,value=${{ steps.semver.outputs.major }}-debug,enable=${{ endsWith(matrix.tag, '-debug') }}
            type=raw,value=${{ steps.semver.outputs.major }}-slim,enable=${{ endsWith(matrix.tag, '-slim') }}
            type=raw,value=latest,enable=${{ matrix.tag == env.IMAGE_LATEST_TAG }}
            type=raw,value=debug,enable=${{ endsWith(matrix.tag, '-debug') }}
            type=raw,value=slim,enable=${{ endsWith(matrix.tag, '-slim') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ACR Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.verystar.net
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ env.IMAGE_NAME }}"
          push: true
          platforms: linux/amd64
          # linux/arm64
          build-args: |
            VERSION=${{ matrix.tag }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
