name: OpenjdkToolkit

on:
  workflow_dispatch:
    inputs:
      target:
        description: "选择要构建的目标"
        type: choice
        default: all
        options:
          - all
          - 8
          - 11
          - 14
          - 15
          - 17

permissions:
  packages: write

env:
  IMAGE_NAME: openjdk

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.target == 'all' || matrix.jdk == github.event.inputs.target }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - jdk: 8
            openjdk_version: 8u362
            gradle_version: 7.4.2
            maven_version: 3.8.8
          - jdk: 11
            openjdk_version: 11.0.18
            gradle_version: 7.4.2
            maven_version: 3.8.8
          - jdk: 14
            openjdk_version: 14.0.2
            gradle_version: 7.4.2
            maven_version: 3.8.8
          - jdk: 15
            openjdk_version: 15.0.2
            gradle_version: 7.4.2
            maven_version: 3.8.8
          - jdk: 17
            openjdk_version: 17.0.6
            gradle_version: 7.4.2
            maven_version: 3.8.8
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
            verystar/${{ env.IMAGE_NAME }}
            registry.verystar.net/library/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.jdk }}-gradle-${{ matrix.gradle_version }}-maven-${{ matrix.maven_version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ACR Container Registry
        uses: docker/login-action@v4
        with:
          registry: registry.verystar.net
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: "{{defaultContext}}:openjdk/toolkit"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            openjdk_version=${{ matrix.openjdk_version }}
            gradle_version=${{ matrix.gradle_version }}
            maven_version=${{ matrix.maven_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
