name: Ubuntu

on:
  push:
    branches:
      - main
    paths:
      - "ubuntu/**"
      - ".github/workflows/ubuntu.yaml"
  workflow_dispatch:

permissions:
  packages: write

env:
  IMAGE_NAME: ubuntu
  IMAGE_LATEST_TAG: 24.04

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - version: 24.04
          # - version: 23.04
          - version: 22.04
          - version: 20.04
          - version: 18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node Version
        uses: actions/setup-node@v5
        with:
          node-version: 18.x

      - name: Get Semver Version
        uses: olegsu/semver-action@v1
        id: get-version
        with:
          version: ${{ matrix.version }}

      - name: Semver Parse
        uses: terradatum/semver-action@main
        id: semver
        with:
          version: ${{ steps.get-version.outputs.version }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}
            verystar/${{ env.IMAGE_NAME }}
            registry.verystar.net/library/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.version }}
            type=raw,value=${{ steps.semver.outputs.major }}
            type=raw,value=latest,enable=${{ matrix.version == env.IMAGE_LATEST_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ACR Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.verystar.net
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ env.IMAGE_NAME }}"
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
